# Generated by Django 5.2.4 on 2026-05-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityofintegration',
            name='academic_year',
        ),
    ]
