# Generated by Django 5.2.4 on 2026-05-10 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_competencyarea_activityofintegration_competency_area'),
        ('members', '0011_student_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='exam',
            name='class_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='members.class'),
            preserve_default=False,
        ),
    ]
