# Generated by Django 5.2.4 on 2026-05-12 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_exam_academic_year_exam_class_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencyarea',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competency_areas', to='exams.topics'),
        ),
    ]
