# Generated by Django 5.2.4 on 2026-05-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_competencyarea_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityofintegration',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='activityofintegration',
            name='task_description',
        ),
        migrations.RemoveField(
            model_name='activityofintegration',
            name='title',
        ),
    ]
