# Generated by Django 5.2.4 on 2026-05-18 18:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_remove_activityofintegration_scenario_and_more'),
        ('members', '0014_subjectpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaperScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_scores', to='exams.exam')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='members.subjectpaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_scores', to='members.student')),
            ],
            options={
                'verbose_name': 'Exam Paper Score',
                'verbose_name_plural': 'Exam Paper Scores',
                'unique_together': {('exam', 'student', 'paper')},
            },
        ),
    ]
