# Generated by Django 5.2.4 on 2026-05-19 05:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exampaperscore'),
        ('expenses', '0003_term_is_current'),
        ('members', '0014_subjectpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_box', models.DecimalField(decimal_places=2, default=10.0, help_text='Scaling divisor factor', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.academicyear')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sa_assessments', to='members.stream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sa_assessments', to='members.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sa_assessments', to='members.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.term')),
            ],
            options={
                'unique_together': {('stream', 'subject', 'term', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ProjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_number', models.PositiveIntegerField(help_text='Competency index, e.g., 1, 2, 3, or 4')),
                ('sub_criteria', models.CharField(help_text="Specific criteria code, e.g., '1.8'", max_length=10)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_scores', to='members.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_scores', to='members.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.term')),
            ],
            options={
                'indexes': [models.Index(fields=['subject', 'term', 'academic_year'], name='exams_proje_subject_faea1f_idx'), models.Index(fields=['student', 'competency_number'], name='exams_proje_student_81cf0a_idx')],
                'unique_together': {('student', 'subject', 'term', 'academic_year', 'sub_criteria')},
            },
        ),
        migrations.CreateModel(
            name='SaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('g1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('l2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('g2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('l3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('g3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('l4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('g4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('l5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('g5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sa_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='exams.saassessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sa_scores', to='members.student')),
            ],
            options={
                'unique_together': {('sa_assessment', 'student')},
            },
        ),
    ]
