# Generated by Django 5.2.4 on 2026-05-19 07:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_saassessment_projectscore_sascore'),
    ]

    operations = [
        migrations.AddField(
            model_name='saassessment',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
