# Generated by Django 5.2.4 on 2026-05-23 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_saassessment_public_id'),
        ('expenses', '0004_academicyear_school_alter_academicyear_name_and_more'),
        ('members', '0016_teacher_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencyarea',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competency_areas', to='members.class'),
        ),
        migrations.AddField(
            model_name='competencyarea',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competency_areas', to='expenses.term'),
        ),
    ]
