# Generated by Django 5.2.4 on 2026-05-31 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_competencyarea_class_obj_competencyarea_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityofintegration',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_aois', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saassessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sas', to=settings.AUTH_USER_MODEL),
        ),
    ]
