# Generated by Django 5.2.4 on 2026-06-01 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_projectscore_created_by'),
        ('expenses', '0004_academicyear_school_alter_academicyear_name_and_more'),
        ('members', '0016_teacher_campus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=50, unique=True)),
                ('name', models.CharField(help_text="e.g., 'Soap Making Project', 'Design a basic website'", max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='projectscore',
            name='exams_proje_subject_faea1f_idx',
        ),
        migrations.AddField(
            model_name='projectscore',
            name='scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='competency_number',
            field=models.PositiveIntegerField(help_text='1 (C1), 2 (C2), 3 (C3), or 4 (C4)'),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_scores_new', to='members.student'),
        ),
        migrations.AddField(
            model_name='project',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.academicyear'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='members.stream'),
        ),
        migrations.AddField(
            model_name='project',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='members.subject'),
        ),
        migrations.AddField(
            model_name='project',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.term'),
        ),
        migrations.AlterUniqueTogether(
            name='projectscore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectscore',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='exams.project'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='projectscore',
            unique_together={('project', 'student', 'competency_number')},
        ),
        migrations.AddIndex(
            model_name='projectscore',
            index=models.Index(fields=['project', 'competency_number'], name='exams_proje_project_09d5d2_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['stream', 'subject', 'academic_year'], name='exams_proje_stream__58a1f6_idx'),
        ),
        migrations.RemoveField(
            model_name='projectscore',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='projectscore',
            name='score',
        ),
        migrations.RemoveField(
            model_name='projectscore',
            name='sub_criteria',
        ),
        migrations.RemoveField(
            model_name='projectscore',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='projectscore',
            name='term',
        ),
    ]
