# Generated by Django 5.2.4 on 2026-06-01 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_project_and_more'),
        ('expenses', '0004_academicyear_school_alter_academicyear_name_and_more'),
        ('members', '0016_teacher_campus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='project',
            name='exams_proje_stream__58a1f6_idx',
        ),
        migrations.RemoveField(
            model_name='project',
            name='academic_year',
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['stream', 'subject'], name='exams_proje_stream__cec93f_idx'),
        ),
    ]
