# Generated by Django 5.2.3 on 2025-06-29 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetupSteps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic_info_completed", models.BooleanField(default=False)),
                ("campus_setup_completed", models.BooleanField(default=False)),
                ("staff_setup_completed", models.BooleanField(default=False)),
                ("student_setup_completed", models.BooleanField(default=False)),
                ("permissions_setup_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Setup Steps",
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_schools",
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campuses",
                        to="accounts.school",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Campuses",
            },
        ),
        migrations.AddField(
            model_name="role",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="accounts.school",
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["school"], name="accounts_ro_school__efe557_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["is_superadmin"], name="accounts_ro_is_supe_6fbd3d_idx"
            ),
        ),
        migrations.AddField(
            model_name="setupsteps",
            name="school",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="setup_steps",
                to="accounts.school",
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["owner"], name="accounts_sc_owner_i_3d8c82_idx"),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["is_active"], name="accounts_sc_is_acti_a937c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campus",
            index=models.Index(
                fields=["school"], name="accounts_ca_school__430b1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campus",
            index=models.Index(
                fields=["is_active"], name="accounts_ca_is_acti_a7b3d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="setupsteps",
            index=models.Index(
                fields=["school"], name="accounts_se_school__4d4b2c_idx"
            ),
        ),
    ]
