# Generated by Django 5.2.4 on 2026-05-21 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_employee_id_alter_customuser_email_and_more'),
        ('schools', '0005_school_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='schools.school'),
        ),
    ]
