# Generated by Django 5.2.4 on 2026-05-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_role_school'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_teacher'], name='accounts_cu_is_teac_350fd5_idx'),
        ),
    ]
