# Generated by Django 5.2.3 on 2025-06-30 20:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_setupsteps_school_campus_role_school_and_more"),
        ("expenses", "0002_academicyear_alter_term_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("level", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="accounts.school",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Classes",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("guardian", "Guardian"),
                            ("grandparent", "Grandparent"),
                            ("uncle", "Uncle"),
                            ("aunt", "Aunt"),
                            ("sibling", "Sibling"),
                            ("other", "Other"),
                        ],
                        default="father",
                        max_length=20,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=200, null=True)),
                ("workplace", models.CharField(blank=True, max_length=200, null=True)),
                ("work_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("home_address", models.TextField(blank=True, null=True)),
                ("is_primary_contact", models.BooleanField(default=True)),
                ("is_emergency_contact", models.BooleanField(default=True)),
                ("is_authorized_pickup", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_profile",
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("capacity", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="expenses.academicyear",
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="accounts.campus",
                    ),
                ),
                (
                    "class_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="members.class",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Streams",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "admission_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("admission_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "previous_school",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("special_needs", models.TextField(blank=True, null=True)),
                ("medical_conditions", models.TextField(blank=True, null=True)),
                ("allergies", models.TextField(blank=True, null=True)),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("transferred", "Transferred"),
                            ("graduated", "Graduated"),
                            ("dropped", "Dropped Out"),
                            ("suspended", "Suspended"),
                        ],
                        default="enrolled",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_stream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="members.stream",
                    ),
                ),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParentStudentRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("guardian", "Guardian"),
                            ("grandparent", "Grandparent"),
                            ("uncle", "Uncle"),
                            ("aunt", "Aunt"),
                            ("sibling", "Sibling"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_emergency_contact", models.BooleanField(default=True)),
                ("is_authorized_pickup", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_student_relationships",
                        to="members.parent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_student_relationships",
                        to="members.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentStreamHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("graduation_date", models.DateField(blank=True, null=True)),
                ("final_grade", models.CharField(blank=True, max_length=10, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments",
                        to="expenses.academicyear",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_history",
                        to="members.stream",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_history",
                        to="members.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Student Stream Histories",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="accounts.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("hire_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "qualification",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("years_of_experience", models.PositiveIntegerField(default=0)),
                ("previous_experience", models.TextField(blank=True, null=True)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("substitute", "Substitute"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stream",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_streams",
                to="members.teacher",
            ),
        ),
        migrations.CreateModel(
            name="TeacherSubjectAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_assignments",
                        to="expenses.academicyear",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_assignments",
                        to="members.stream",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_assignments",
                        to="members.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_assignments",
                        to="members.teacher",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["school", "level"], name="members_cla_school__7350ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["is_active"], name="members_cla_is_acti_c90712_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("name", "school")},
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["relationship_type"], name="members_par_relatio_037d99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["is_primary_contact", "is_active"],
                name="members_par_is_prim_8916dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["student_id"], name="members_stu_student_312356_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["current_stream", "is_active"],
                name="members_stu_current_3a5a65_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["enrollment_status"], name="members_stu_enrollm_eb9b9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["admission_date"], name="members_stu_admissi_9ad795_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parentstudentrelationship",
            index=models.Index(
                fields=["student", "is_primary"], name="members_par_student_c2be0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parentstudentrelationship",
            index=models.Index(
                fields=["parent"], name="members_par_parent__ff07dd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="parentstudentrelationship",
            unique_together={("parent", "student")},
        ),
        migrations.AddIndex(
            model_name="studentstreamhistory",
            index=models.Index(
                fields=["student", "academic_year"],
                name="members_stu_student_5d1016_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentstreamhistory",
            index=models.Index(
                fields=["stream", "academic_year"],
                name="members_stu_stream__465500_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentstreamhistory",
            index=models.Index(
                fields=["is_active"], name="members_stu_is_acti_5808a8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentstreamhistory",
            unique_together={("student", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["school", "is_active"], name="members_sub_school__6f37a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["code"], name="members_sub_code_71faf4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("code", "school")},
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["employee_id"], name="members_tea_employe_93d6c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["employment_type", "is_active"],
                name="members_tea_employm_57c8b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["hire_date"], name="members_tea_hire_da_88ef6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stream",
            index=models.Index(
                fields=["class_level", "academic_year"],
                name="members_str_class_l_ab98ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stream",
            index=models.Index(
                fields=["campus", "is_active"], name="members_str_campus__f432a7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stream",
            unique_together={("name", "class_level", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="teachersubjectassignment",
            index=models.Index(
                fields=["teacher", "academic_year"],
                name="members_tea_teacher_fb27db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubjectassignment",
            index=models.Index(
                fields=["stream", "academic_year"],
                name="members_tea_stream__ca923b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubjectassignment",
            index=models.Index(
                fields=["subject", "is_active"], name="members_tea_subject_1811f6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teachersubjectassignment",
            unique_together={("teacher", "subject", "stream", "academic_year")},
        ),
    ]
