# Generated by Django 5.2.3 on 2025-06-30 21:10

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="admission_date",
            field=models.DateField(default=members.models.get_current_date),
        ),
        migrations.AlterField(
            model_name="studentstreamhistory",
            name="enrollment_date",
            field=models.DateField(default=members.models.get_current_date),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="hire_date",
            field=models.DateField(default=members.models.get_current_date),
        ),
    ]
