# Generated by Django 5.2.3 on 2025-07-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_setupsteps_school_campus_role_school_and_more"),
        ("members", "0002_alter_student_admission_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="parent_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, null=True, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["parent_id"], name="members_par_parent__cb3662_idx"
            ),
        ),
    ]
