# Generated by Django 5.2.3 on 2025-07-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_add_parent_id_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("substitute", "Substitute"),
                    ("volunteer", "Volunteer"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
    ]
