# Generated by Django 5.2.3 on 2025-07-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_teacher_employment_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"verbose_name_plural": "Classes"},
        ),
        migrations.RemoveIndex(
            model_name="class",
            name="members_cla_school__7350ba_idx",
        ),
        migrations.RemoveIndex(
            model_name="stream",
            name="members_str_class_l_ab98ed_idx",
        ),
        migrations.RemoveIndex(
            model_name="stream",
            name="members_str_campus__f432a7_idx",
        ),
        migrations.RenameField(
            model_name="stream",
            old_name="class_level",
            new_name="class_obj",
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="stream",
            unique_together={("name", "class_obj")},
        ),
        migrations.AddIndex(
            model_name="stream",
            index=models.Index(
                fields=["class_obj", "is_active"], name="members_str_class_o_c59821_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="class",
            name="level",
        ),
        migrations.RemoveField(
            model_name="class",
            name="school",
        ),
        migrations.RemoveField(
            model_name="stream",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="stream",
            name="campus",
        ),
    ]
