# Generated by Django 5.2.4 on 2025-07-16 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_setupsteps_school_campus_role_school_and_more"),
        ("expenses", "0003_term_is_current"),
        ("members", "0005_alter_class_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryAllowance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "allowance_type",
                    models.CharField(
                        choices=[
                            ("housing", "Housing Allowance"),
                            ("transport", "Transport Allowance"),
                            ("medical", "Medical Allowance"),
                            ("responsibility", "Responsibility Allowance"),
                            ("overtime", "Overtime Allowance"),
                            ("bonus", "Bonus"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_percentage", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SalaryDeduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "deduction_type",
                    models.CharField(
                        choices=[
                            ("tax", "Tax"),
                            ("insurance", "Insurance"),
                            ("pension", "Pension"),
                            ("loan", "Loan Repayment"),
                            ("advance", "Salary Advance"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_percentage", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SalaryPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("mobile_money", "Mobile Money"),
                            ("other", "Other"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "receipt_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="salary_receipts/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalaryPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SalarySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_base_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_net_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_staff", models.PositiveIntegerField(default=0)),
                ("paid_staff", models.PositiveIntegerField(default=0)),
                ("pending_staff", models.PositiveIntegerField(default=0)),
                (
                    "average_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_completion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-salary_period__start_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="teachersubjectassignment",
            options={"ordering": ["teacher", "subject", "stream"]},
        ),
        migrations.RemoveIndex(
            model_name="teachersubjectassignment",
            name="members_tea_teacher_fb27db_idx",
        ),
        migrations.RemoveIndex(
            model_name="teachersubjectassignment",
            name="members_tea_stream__ca923b_idx",
        ),
        migrations.RemoveIndex(
            model_name="teachersubjectassignment",
            name="members_tea_subject_1811f6_idx",
        ),
        migrations.AddField(
            model_name="salarypayment",
            name="processed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_salary_payments",
                to="accounts.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="salarypayment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_payments",
                to="members.teacher",
            ),
        ),
        migrations.AddField(
            model_name="salaryperiod",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_periods",
                to="expenses.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="salaryperiod",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_periods",
                to="expenses.term",
            ),
        ),
        migrations.AddField(
            model_name="salarypayment",
            name="salary_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="members.salaryperiod",
            ),
        ),
        migrations.AddField(
            model_name="salarysummary",
            name="salary_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summaries",
                to="members.salaryperiod",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salaryperiod",
            unique_together={("name", "academic_year")},
        ),
        migrations.AlterUniqueTogether(
            name="salarypayment",
            unique_together={("teacher", "salary_period")},
        ),
        migrations.AlterUniqueTogether(
            name="salarysummary",
            unique_together={("salary_period",)},
        ),
    ]
