# Generated by Django 5.2.4 on 2025-07-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_term_is_current"),
        ("members", "0007_add_non_staff_member_only"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SalaryAllowance",
        ),
        migrations.DeleteModel(
            name="SalaryDeduction",
        ),
        migrations.AlterUniqueTogether(
            name="salarypayment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="salarypayment",
            name="processed_by",
        ),
        migrations.RemoveField(
            model_name="salarypayment",
            name="salary_period",
        ),
        migrations.RemoveField(
            model_name="salarypayment",
            name="teacher",
        ),
        migrations.AlterUniqueTogether(
            name="salaryperiod",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="salaryperiod",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="salaryperiod",
            name="term",
        ),
        migrations.RemoveField(
            model_name="salarysummary",
            name="salary_period",
        ),
        migrations.AlterUniqueTogether(
            name="salarysummary",
            unique_together=None,
        ),
        migrations.AlterModelOptions(
            name="teachersubjectassignment",
            options={},
        ),
        migrations.AddIndex(
            model_name="teachersubjectassignment",
            index=models.Index(
                fields=["teacher", "academic_year"],
                name="members_tea_teacher_fb27db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubjectassignment",
            index=models.Index(
                fields=["stream", "academic_year"],
                name="members_tea_stream__ca923b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubjectassignment",
            index=models.Index(
                fields=["subject", "is_active"], name="members_tea_subject_1811f6_idx"
            ),
        ),
        migrations.DeleteModel(
            name="SalaryPayment",
        ),
        migrations.DeleteModel(
            name="SalaryPeriod",
        ),
        migrations.DeleteModel(
            name="SalarySummary",
        ),
    ]
