# Generated by Django 5.2.4 on 2025-07-30 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_setupsteps_school_campus_role_school_and_more"),
        ("expenses", "0003_term_is_current"),
        ("members", "0007_add_non_staff_member_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryPaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="teachersubjectassignment",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="salarypayment",
            unique_together={("teacher", "salary_period")},
        ),
        migrations.RemoveField(
            model_name="salaryperiod",
            name="is_paid",
        ),
        migrations.AddField(
            model_name="salarypayment",
            name="non_staff_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_payments",
                to="members.nonstaffmember",
            ),
        ),
        migrations.AddField(
            model_name="salaryperiod",
            name="is_closed",
            field=models.BooleanField(
                default=False, help_text="Closed periods cannot be modified"
            ),
        ),
        migrations.AddField(
            model_name="salarysummary",
            name="net_income",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="salarysummary",
            name="total_fee_collection",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="nonstaffmember",
            name="salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Salary amount in Ugandan Shillings (UGX)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salaryallowance",
            name="is_percentage",
            field=models.BooleanField(
                default=False, help_text="If True, amount is percentage of base salary"
            ),
        ),
        migrations.AlterField(
            model_name="salarydeduction",
            name="deduction_type",
            field=models.CharField(
                choices=[
                    ("tax", "Income Tax"),
                    ("nssf", "NSSF"),
                    ("nhif", "NHIF"),
                    ("loan", "Loan Repayment"),
                    ("advance", "Salary Advance"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salarydeduction",
            name="is_percentage",
            field=models.BooleanField(
                default=False, help_text="If True, amount is percentage of base salary"
            ),
        ),
        migrations.AlterField(
            model_name="salarypayment",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_payments",
                to="members.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="salarysummary",
            name="salary_period",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summary",
                to="members.salaryperiod",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Salary amount in Ugandan Shillings (UGX)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salarypayment",
            unique_together={
                ("non_staff_member", "salary_period"),
                ("teacher", "salary_period"),
            },
        ),
        migrations.AddIndex(
            model_name="salaryallowance",
            index=models.Index(
                fields=["allowance_type", "is_active"],
                name="members_sal_allowan_e67a31_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salarydeduction",
            index=models.Index(
                fields=["deduction_type", "is_active"],
                name="members_sal_deducti_17fe44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salarypayment",
            index=models.Index(
                fields=["payment_status"], name="members_sal_payment_09275f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salarypayment",
            index=models.Index(
                fields=["payment_date"], name="members_sal_payment_0f57e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salarypayment",
            index=models.Index(
                fields=["teacher", "salary_period"],
                name="members_sal_teacher_d59612_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salarypayment",
            index=models.Index(
                fields=["non_staff_member", "salary_period"],
                name="members_sal_non_sta_fc8041_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salaryperiod",
            index=models.Index(
                fields=["academic_year", "term"], name="members_sal_academi_2cf098_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salaryperiod",
            index=models.Index(
                fields=["start_date", "end_date"], name="members_sal_start_d_e40a48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salarysummary",
            index=models.Index(
                fields=["total_net_salary"], name="members_sal_total_n_015e48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salarysummary",
            index=models.Index(
                fields=["payment_completion_rate"],
                name="members_sal_payment_48d21e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubjectassignment",
            index=models.Index(
                fields=["teacher", "academic_year"],
                name="members_tea_teacher_fb27db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubjectassignment",
            index=models.Index(
                fields=["stream", "academic_year"],
                name="members_tea_stream__ca923b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teachersubjectassignment",
            index=models.Index(
                fields=["subject", "is_active"], name="members_tea_subject_1811f6_idx"
            ),
        ),
        migrations.AddField(
            model_name="salarypaymentdetail",
            name="allowance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_details",
                to="members.salaryallowance",
            ),
        ),
        migrations.AddField(
            model_name="salarypaymentdetail",
            name="deduction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_details",
                to="members.salarydeduction",
            ),
        ),
        migrations.AddField(
            model_name="salarypaymentdetail",
            name="salary_payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="members.salarypayment",
            ),
        ),
        migrations.AddIndex(
            model_name="salarypaymentdetail",
            index=models.Index(
                fields=["salary_payment"], name="members_sal_salary__12dd1a_idx"
            ),
        ),
    ]
