# Generated by Django 5.2.4 on 2025-07-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_delete_salaryallowance_delete_salarydeduction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonstaffmember",
            name="salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Salary amount in Ugandan Shillings (UGX)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Salary amount in Ugandan Shillings (UGX)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
