# Generated by Django 5.2.4 on 2026-05-09 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_salarypaymentdetail_and_more'),
        ('schools', '0002_document_alter_campus_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school'),
        ),
    ]
