# Generated by Django 5.2.4 on 2026-05-10 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_subject_school'),
        ('schools', '0002_document_alter_campus_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.campus'),
            preserve_default=False,
        ),
    ]
