# Generated by Django 5.2.4 on 2025-07-18 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_setupsteps_school_campus_role_school_and_more"),
        ("expenses", "0003_term_is_current"),
        ("members", "0009_alter_nonstaffmember_salary_alter_teacher_salary"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryAllowance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "allowance_type",
                    models.CharField(
                        choices=[
                            ("housing", "Housing Allowance"),
                            ("transport", "Transport Allowance"),
                            ("medical", "Medical Allowance"),
                            ("responsibility", "Responsibility Allowance"),
                            ("overtime", "Overtime Allowance"),
                            ("bonus", "Bonus"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "is_percentage",
                    models.BooleanField(
                        default=False,
                        help_text="If True, amount is percentage of base salary",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["allowance_type", "is_active"],
                        name="members_sal_allowan_e67a31_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SalaryDeduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "deduction_type",
                    models.CharField(
                        choices=[
                            ("tax", "Income Tax"),
                            ("nssf", "NSSF"),
                            ("nhif", "NHIF"),
                            ("loan", "Loan Repayment"),
                            ("advance", "Salary Advance"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "is_percentage",
                    models.BooleanField(
                        default=False,
                        help_text="If True, amount is percentage of base salary",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["deduction_type", "is_active"],
                        name="members_sal_deducti_17fe44_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SalaryPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "period_type",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("termly", "Termly")],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False, help_text="Closed periods cannot be modified"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_periods",
                        to="expenses.academicyear",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_periods",
                        to="expenses.term",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SalaryPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("mobile_money", "Mobile Money"),
                            ("other", "Other"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "receipt_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="salary_receipts/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "non_staff_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_payments",
                        to="members.nonstaffmember",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_salary_payments",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_payments",
                        to="members.teacher",
                    ),
                ),
                (
                    "salary_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="members.salaryperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalarySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_base_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_net_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_staff", models.PositiveIntegerField(default=0)),
                ("paid_staff", models.PositiveIntegerField(default=0)),
                ("pending_staff", models.PositiveIntegerField(default=0)),
                (
                    "average_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_completion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_fee_collection",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "net_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "salary_period",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="members.salaryperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-salary_period__start_date"],
            },
        ),
        migrations.CreateModel(
            name="SalaryPaymentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allowance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_details",
                        to="members.salaryallowance",
                    ),
                ),
                (
                    "deduction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_details",
                        to="members.salarydeduction",
                    ),
                ),
                (
                    "salary_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="members.salarypayment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["salary_payment"], name="members_sal_salary__12dd1a_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="salaryperiod",
            index=models.Index(
                fields=["period_type", "is_active"],
                name="members_sal_period__3c56b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salaryperiod",
            index=models.Index(
                fields=["academic_year", "term"], name="members_sal_academi_2cf098_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salaryperiod",
            index=models.Index(
                fields=["start_date", "end_date"], name="members_sal_start_d_e40a48_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salaryperiod",
            unique_together={("name", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="salarypayment",
            index=models.Index(
                fields=["payment_status"], name="members_sal_payment_09275f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salarypayment",
            index=models.Index(
                fields=["payment_date"], name="members_sal_payment_0f57e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salarypayment",
            index=models.Index(
                fields=["teacher", "salary_period"],
                name="members_sal_teacher_d59612_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salarypayment",
            index=models.Index(
                fields=["non_staff_member", "salary_period"],
                name="members_sal_non_sta_fc8041_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salarypayment",
            unique_together={
                ("non_staff_member", "salary_period"),
                ("teacher", "salary_period"),
            },
        ),
        migrations.AddIndex(
            model_name="salarysummary",
            index=models.Index(
                fields=["total_net_salary"], name="members_sal_total_n_015e48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salarysummary",
            index=models.Index(
                fields=["payment_completion_rate"],
                name="members_sal_payment_48d21e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salarysummary",
            unique_together={("salary_period",)},
        ),
    ]
