# Generated by Django 5.2.4 on 2026-05-10 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_class_campus'),
        ('schools', '0002_document_alter_campus_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.campus'),
        ),
    ]
