# Generated by Django 5.2.4 on 2025-07-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0010_salaryallowance_salarydeduction_salaryperiod_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salaryperiod",
            name="period_type",
        ),
    ]
