# Generated by Django 5.2.4 on 2025-07-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0011_remove_period_type_field"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="salaryperiod",
            name="members_sal_period__3c56b5_idx",
        ),
    ]
