# Generated by Django 5.2.4 on 2026-05-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='level',
            field=models.CharField(blank=True, choices=[('0level', '0level'), ('Alevel', 'Alevel')], max_length=50, null=True),
        ),
    ]
