# Generated by Django 5.2.4 on 2025-07-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_salaryperiod_members_sal_period__3c56b5_idx'),
    ]

    operations = [
        # Add the is_closed field
        migrations.AddField(
            model_name='salaryperiod',
            name='is_closed',
            field=models.BooleanField(
                default=False,
                help_text='Closed periods cannot be modified'
            ),
        ),
    ]
