# Generated by Django 5.2.4 on 2025-07-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_add_is_closed_to_salary_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='members.salaryallowance')),
                ('deduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='members.salarydeduction')),
                ('salary_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='members.salarypayment')),
            ],
            options={
                'indexes': [models.Index(fields=['salary_payment'], name='members_sal_salary__f8c8c8_idx')],
            },
        ),
    ]
