# Generated by Django 5.2.4 on 2026-05-18 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_class_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the paper, e.g., 'Paper 1', 'Paper 2'", max_length=100)),
                ('code', models.CharField(blank=True, help_text="Official paper code, e.g., 'P425/1'", max_length=20, null=True)),
                ('max_score', models.PositiveIntegerField(default=100, help_text='Maximum raw marks achievable in this paper')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='members.subject')),
            ],
            options={
                'verbose_name': 'Subject Paper',
                'verbose_name_plural': 'Subject Papers',
                'unique_together': {('subject', 'name')},
            },
        ),
    ]
