# Generated by Django 5.2.4 on 2026-05-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_subjectpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lin',
            field=models.CharField(blank=True, help_text='Learners Identification Number', max_length=50, null=True, verbose_name='Learner Identification Number (LIN)'),
        ),
    ]
