# Generated by Django 5.2.4 on 2025-07-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0014_add_salary_payment_detail_table"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="salarypaymentdetail",
            new_name="members_sal_salary__12dd1a_idx",
            old_name="members_sal_salary__f8c8c8_idx",
        ),
    ]
