# Generated by Django 5.2.4 on 2026-05-23 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_student_lin'),
        ('schools', '0005_school_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='schools.campus'),
        ),
    ]
