# Generated by Django 5.2.3 on 2025-06-29 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_remove_campus_school_remove_school_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_schools",
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campuses",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Campuses",
            },
        ),
        migrations.CreateModel(
            name="SetupSteps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic_info_completed", models.BooleanField(default=False)),
                ("campus_setup_completed", models.BooleanField(default=False)),
                ("staff_setup_completed", models.BooleanField(default=False)),
                ("student_setup_completed", models.BooleanField(default=False)),
                ("permissions_setup_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setup_steps",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Setup Steps",
            },
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["owner"], name="schools_sch_owner_i_bd0dc7_idx"),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["is_active"], name="schools_sch_is_acti_522730_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campus",
            index=models.Index(
                fields=["school"], name="schools_cam_school__e180ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campus",
            index=models.Index(
                fields=["is_active"], name="schools_cam_is_acti_2e4a6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="setupsteps",
            index=models.Index(
                fields=["school"], name="schools_set_school__539f21_idx"
            ),
        ),
    ]
