# Generated by Django 5.2.4 on 2026-05-06 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('doc_name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(max_length=100)),
                ('doc_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['name'], 'verbose_name': 'Campus', 'verbose_name_plural': 'Campuses'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelOptions(
            name='setupsteps',
            options={'ordering': ['-created_at'], 'verbose_name': 'Setup Step', 'verbose_name_plural': 'Setup Steps'},
        ),
        migrations.RemoveIndex(
            model_name='campus',
            name='schools_cam_school__e180ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='campus',
            name='schools_cam_is_acti_2e4a6a_idx',
        ),
        migrations.RemoveIndex(
            model_name='school',
            name='schools_sch_owner_i_bd0dc7_idx',
        ),
        migrations.RemoveIndex(
            model_name='school',
            name='schools_sch_is_acti_522730_idx',
        ),
        migrations.RemoveIndex(
            model_name='setupsteps',
            name='schools_set_school__539f21_idx',
        ),
        migrations.RenameField(
            model_name='campus',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='campus',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='setupsteps',
            old_name='basic_info_completed',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='school',
        ),
        migrations.RemoveField(
            model_name='school',
            name='website',
        ),
        migrations.AddField(
            model_name='campus',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Optional campus affiliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='schools.campus'),
        ),
        migrations.AddField(
            model_name='school',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='setupsteps',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setupsteps',
            name='setup_name',
            field=models.CharField(default='first', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='setupsteps',
            unique_together={('school', 'setup_name')},
        ),
        migrations.AlterField(
            model_name='campus',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(default='MAIN CAMPUS', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setupsteps',
            name='school',
            field=models.ForeignKey(help_text='School this setup belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='setup_steps', to='schools.school'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='setupsteps',
            name='campus_setup_completed',
        ),
        migrations.RemoveField(
            model_name='setupsteps',
            name='permissions_setup_completed',
        ),
        migrations.RemoveField(
            model_name='setupsteps',
            name='staff_setup_completed',
        ),
        migrations.RemoveField(
            model_name='setupsteps',
            name='student_setup_completed',
        ),
    ]
