# Generated by Django 5.2.4 on 2026-05-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_document_alter_campus_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='report_accent_color',
            field=models.CharField(default='#4f46e5', max_length=7),
        ),
        migrations.AddField(
            model_name='school',
            name='report_primary_color',
            field=models.CharField(default='#185FA5', max_length=7),
        ),
    ]
