# Generated by Django 5.2.4 on 2026-05-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_report_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, help_text='School logo used in report header and watermark', null=True, upload_to='schools/logos/'),
        ),
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, help_text='School motto displayed on report cards', max_length=255, null=True),
        ),
    ]
