# Generated by Django 5.2.4 on 2026-05-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_logo_school_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='level',
            field=models.CharField(default='secondary', max_length=20),
        ),
    ]
