# Generated by Django 5.2.4 on 2025-07-13 18:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_academicyear_alter_term_options_and_more"),
        ("fees", "0001_initial"),
        ("members", "0005_alter_class_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentFeeBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_expected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_discounts",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_pending",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "balance_status",
                    models.CharField(
                        choices=[
                            ("paid", "Fully Paid"),
                            ("partial", "Partially Paid"),
                            ("unpaid", "Unpaid"),
                            ("overpaid", "Overpaid"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_fee_balances",
                        to="expenses.academicyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_balances",
                        to="members.student",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_fee_balances",
                        to="expenses.term",
                    ),
                ),
            ],
            options={
                "ordering": ["student", "academic_year", "term"],
                "indexes": [
                    models.Index(
                        fields=["student", "academic_year", "term"],
                        name="fees_studen_student_c78465_idx",
                    ),
                    models.Index(
                        fields=["balance_status"], name="fees_studen_balance_edd59e_idx"
                    ),
                    models.Index(
                        fields=["total_pending"], name="fees_studen_total_p_eab4f1_idx"
                    ),
                ],
                "unique_together": {("student", "academic_year", "term")},
            },
        ),
    ]
