# Generated by Django 5.2.4 on 2025-07-14 18:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_academicyear_alter_term_options_and_more"),
        ("fees", "0002_studentfeebalance"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermFeeCollectionSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_expected_from_structures",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_expected_with_overrides",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_discounts_given",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_pending_collection",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("students_with_fees", models.PositiveIntegerField(default=0)),
                ("fully_paid_students", models.PositiveIntegerField(default=0)),
                ("partially_paid_students", models.PositiveIntegerField(default=0)),
                ("unpaid_students", models.PositiveIntegerField(default=0)),
                ("overpaid_students", models.PositiveIntegerField(default=0)),
                (
                    "collection_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "average_payment_per_student",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_collection_summaries",
                        to="expenses.academicyear",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_collection_summaries",
                        to="expenses.term",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Term Fee Collection Summaries",
                "ordering": ["academic_year", "term"],
                "indexes": [
                    models.Index(
                        fields=["academic_year", "term"],
                        name="fees_termfe_academi_7abfd6_idx",
                    ),
                    models.Index(
                        fields=["collection_rate"],
                        name="fees_termfe_collect_620107_idx",
                    ),
                    models.Index(
                        fields=["total_pending_collection"],
                        name="fees_termfe_total_p_1ab31d_idx",
                    ),
                ],
                "unique_together": {("academic_year", "term")},
            },
        ),
    ]
