# Generated by Django 5.2.4 on 2025-07-15 19:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_term_is_current"),
        ("fees", "0003_termfeecollectionsummary"),
        ("members", "0005_alter_class_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentfeeoverride",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="studentfeeoverride",
            name="academic_year",
        ),
        migrations.RemoveField(
            model_name="studentfeeoverride",
            name="category",
        ),
        migrations.RemoveField(
            model_name="studentfeeoverride",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentfeeoverride",
            name="term",
        ),
        migrations.AlterModelOptions(
            name="scholarship",
            options={"ordering": ["name"], "verbose_name_plural": "Scholarships"},
        ),
        migrations.AlterModelOptions(
            name="termfeecollectionsummary",
            options={"ordering": ["-academic_year", "-term"]},
        ),
        migrations.RemoveIndex(
            model_name="termfeecollectionsummary",
            name="fees_termfe_total_p_1ab31d_idx",
        ),
        migrations.RenameField(
            model_name="scholarship",
            old_name="max_discount_amount",
            new_name="max_amount",
        ),
        migrations.RemoveField(
            model_name="feepayment",
            name="recorded_by",
        ),
        migrations.RemoveField(
            model_name="feepayment",
            name="scholarship",
        ),
        migrations.RemoveField(
            model_name="scholarship",
            name="discount_type",
        ),
        migrations.RemoveField(
            model_name="scholarship",
            name="discount_value",
        ),
        migrations.AddField(
            model_name="scholarship",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="termfeecollectionsummary",
            name="collection_efficiency",
            field=models.CharField(
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                ],
                default="fair",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="termfeecollectionsummary",
            name="collection_percentage",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="termfeecollectionsummary",
            name="is_collection_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="termfeecollectionsummary",
            name="outstanding_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="feepayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("mobile_money", "Mobile Money"),
                    ("check", "Check"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="feepayment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="termfeecollectionsummary",
            name="fully_paid_students",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="termfeecollectionsummary",
            name="overpaid_students",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="termfeecollectionsummary",
            name="partially_paid_students",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="termfeecollectionsummary",
            name="students_with_fees",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="termfeecollectionsummary",
            name="total_students",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="termfeecollectionsummary",
            name="unpaid_students",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="feepayment",
            index=models.Index(
                fields=["student", "academic_year", "term"],
                name="fees_feepay_student_dbdaff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feepayment",
            index=models.Index(
                fields=["payment_status"], name="fees_feepay_payment_90881c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feepayment",
            index=models.Index(
                fields=["payment_date"], name="fees_feepay_payment_71212d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feepayment",
            index=models.Index(
                fields=["receipt_number"], name="fees_feepay_receipt_5b901a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="termfeecollectionsummary",
            index=models.Index(
                fields=["is_collection_complete"], name="fees_termfe_is_coll_7c3d76_idx"
            ),
        ),
        migrations.DeleteModel(
            name="StudentFeeOverride",
        ),
    ]
