# Generated by Django 5.2.4 on 2025-07-15 19:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_setupsteps_school_campus_role_school_and_more"),
        ("expenses", "0003_term_is_current"),
        ("fees", "0004_alter_studentfeeoverride_unique_together_and_more"),
        ("members", "0005_alter_class_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentFeeOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["student", "academic_year", "term", "category"],
            },
        ),
        migrations.AlterModelOptions(
            name="scholarship",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="termfeecollectionsummary",
            options={
                "ordering": ["academic_year", "term"],
                "verbose_name_plural": "Term Fee Collection Summaries",
            },
        ),
        migrations.RemoveIndex(
            model_name="feepayment",
            name="fees_feepay_student_dbdaff_idx",
        ),
        migrations.RemoveIndex(
            model_name="feepayment",
            name="fees_feepay_payment_90881c_idx",
        ),
        migrations.RemoveIndex(
            model_name="feepayment",
            name="fees_feepay_payment_71212d_idx",
        ),
        migrations.RemoveIndex(
            model_name="feepayment",
            name="fees_feepay_receipt_5b901a_idx",
        ),
        migrations.RemoveIndex(
            model_name="termfeecollectionsummary",
            name="fees_termfe_is_coll_7c3d76_idx",
        ),
        migrations.RenameField(
            model_name="scholarship",
            old_name="max_amount",
            new_name="max_discount_amount",
        ),
        migrations.RemoveField(
            model_name="scholarship",
            name="discount_percentage",
        ),
        migrations.RemoveField(
            model_name="termfeecollectionsummary",
            name="collection_efficiency",
        ),
        migrations.RemoveField(
            model_name="termfeecollectionsummary",
            name="collection_percentage",
        ),
        migrations.RemoveField(
            model_name="termfeecollectionsummary",
            name="is_collection_complete",
        ),
        migrations.RemoveField(
            model_name="termfeecollectionsummary",
            name="outstanding_amount",
        ),
        migrations.AddField(
            model_name="feepayment",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_payments",
                to="accounts.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="feepayment",
            name="scholarship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="fees.scholarship",
            ),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="discount_type",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage"),
                    ("fixed_amount", "Fixed Amount"),
                ],
                default="percentage",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feepayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cheque", "Cheque"),
                    ("mobile_money", "Mobile Money"),
                    ("credit_card", "Credit Card"),
                    ("other", "Other"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feepayment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="termfeecollectionsummary",
            name="fully_paid_students",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="termfeecollectionsummary",
            name="overpaid_students",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="termfeecollectionsummary",
            name="partially_paid_students",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="termfeecollectionsummary",
            name="students_with_fees",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="termfeecollectionsummary",
            name="total_students",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="termfeecollectionsummary",
            name="unpaid_students",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="termfeecollectionsummary",
            index=models.Index(
                fields=["total_pending_collection"],
                name="fees_termfe_total_p_1ab31d_idx",
            ),
        ),
        migrations.AddField(
            model_name="studentfeeoverride",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_fee_overrides",
                to="expenses.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="studentfeeoverride",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_overrides",
                to="fees.feecategory",
            ),
        ),
        migrations.AddField(
            model_name="studentfeeoverride",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_overrides",
                to="members.student",
            ),
        ),
        migrations.AddField(
            model_name="studentfeeoverride",
            name="term",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_fee_overrides",
                to="expenses.term",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentfeeoverride",
            unique_together={("student", "category", "academic_year", "term")},
        ),
    ]
