# Generated by Django 5.2.4 on 2025-07-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_academicyear_alter_term_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
    ]
