# Generated by Django 5.2.4 on 2026-05-23 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_term_is_current'),
        ('schools', '0005_school_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('name', 'school')},
        ),
    ]
