# Generated by Django 5.2.4 on 2026-05-08 06:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0003_term_is_current'),
        ('members', '0008_salarypaymentdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overall_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('out_of', models.PositiveIntegerField(blank=True, help_text='Total students in the class/stream', null=True)),
                ('class_teacher_remarks', models.TextField(blank=True, null=True)),
                ('head_teacher_remarks', models.TextField(blank=True, null=True)),
                ('attendance_days_present', models.PositiveIntegerField(default=0)),
                ('attendance_total_days', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.class')),
                ('class_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_reports', to='members.teacher')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='members.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.term')),
            ],
            options={
                'ordering': ['-academic_year', '-term', 'student'],
                'unique_together': {('student', 'academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='SubjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoi_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Cumulative score from Activities of Integration (out of 20%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('exam_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Final Exam score (out of 80%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)])),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of AoI (20%) and Exam (80%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_reports', to='reports.reportcard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.teacher')),
            ],
            options={
                'unique_together': {('report_card', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='SubjectCompetencyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_name', models.CharField(max_length=255)),
                ('score', models.DecimalField(decimal_places=2, help_text='The raw score or descriptor for the competency (usually 1, 2, or 3)', max_digits=4)),
                ('descriptor', models.CharField(blank=True, help_text='Basic, Proficient, or Outstanding', max_length=100, null=True)),
                ('subject_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_scores', to='reports.subjectreport')),
            ],
        ),
    ]
