# Generated by Django 5.2.4 on 2026-05-11 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectreport',
            name='aoi_raw_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of raw marks from Activities of Integration', max_digits=5),
        ),
        migrations.AddField(
            model_name='subjectreport',
            name='exam_raw_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Raw Final Exam score (out of 100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
