# Generated by Django 5.2.4 on 2026-05-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_subjectreport_aoi_raw_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcompetencyscore',
            name='descriptor',
        ),
        migrations.AddField(
            model_name='subjectcompetencyscore',
            name='assessment_type',
            field=models.CharField(choices=[('aoi', 'Activity of Integration'), ('exam', 'Examination')], default='aoi', max_length=10),
        ),
        migrations.AddField(
            model_name='subjectcompetencyscore',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Maximum possible raw score for this item', max_digits=5),
        ),
        migrations.AlterField(
            model_name='subjectcompetencyscore',
            name='competency_name',
            field=models.CharField(help_text="Title of the AOI activity or 'Examination'", max_length=255),
        ),
        migrations.AlterField(
            model_name='subjectcompetencyscore',
            name='score',
            field=models.DecimalField(decimal_places=2, help_text='Raw score achieved by the student', max_digits=5),
        ),
    ]
