# Generated by Django 5.2.4 on 2026-05-11 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_subjectcompetencyscore_descriptor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.PositiveIntegerField(blank=True, help_text='Aggregate points (e.g., D1=1, F9=9)', null=True)),
                ('grading_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='reports.gradingsystem')),
            ],
            options={
                'ordering': ['-min_score'],
                'unique_together': {('grading_system', 'grade')},
            },
        ),
    ]
