# Generated by Django 5.2.4 on 2026-05-12 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_gradingsystem_gradeboundary'),
        ('schools', '0002_document_alter_campus_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsystem',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
            preserve_default=False,
        ),
    ]
