# Generated by Django 5.2.4 on 2026-05-16 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_gradingsystem_school'),
        ('schools', '0004_school_logo_school_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeboundary',
            name='description',
            field=models.TextField(blank=True, help_text="Full grade descriptor text shown in the grade key table, e.g. 'Exceptional – Demonstrates mastery...'", null=True),
        ),
        migrations.CreateModel(
            name='ReportCardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_attendance', models.BooleanField(default=True)),
                ('show_grade_descriptor', models.BooleanField(default=True)),
                ('show_grade_descriptor_score_range', models.BooleanField(default=True)),
                ('show_identifier_legend', models.BooleanField(default=True)),
                ('show_subject_teacher_initials', models.BooleanField(default=True)),
                ('show_teacher_comment', models.BooleanField(default=True)),
                ('show_header', models.BooleanField(default=True)),
                ('show_watermark', models.BooleanField(default=False)),
                ('show_school_logo', models.BooleanField(default=True)),
                ('show_school_motto', models.BooleanField(default=True)),
                ('show_overall_student_rank', models.BooleanField(default=True)),
                ('show_stream_student_rank', models.BooleanField(default=False)),
                ('show_division_and_aggregate', models.BooleanField(default=True)),
                ('show_class_teacher_remarks', models.BooleanField(default=True)),
                ('show_head_teacher_remarks', models.BooleanField(default=True)),
                ('show_class_teacher_signature', models.BooleanField(default=True)),
                ('show_head_teacher_signature', models.BooleanField(default=True)),
                ('show_parent_signature', models.BooleanField(default=False)),
                ('show_school_dates', models.BooleanField(default=True)),
                ('show_school_fees', models.BooleanField(default=False)),
                ('school_closed_on', models.DateField(blank=True, null=True)),
                ('next_term_begins_on', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_card_settings', to='schools.school')),
            ],
        ),
    ]
