# Generated by Django 5.2.4 on 2026-05-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_gradeboundary_description_reportcardsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeboundary',
            name='points',
        ),
    ]
