# Generated by Django 5.2.4 on 2026-05-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_gradeboundary_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsystem',
            name='level',
            field=models.CharField(choices=[('O-Level', 'O-Level'), ('A-Level', 'A-Level')], default='O-Level', max_length=20),
        ),
    ]
